
services:
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  app:
    restart: always
    build: .
    command: npm start
    ports:
      - "80:3000"
    links:
      - mongodb



