# To connect the db and other services? like web front end, db 
# Compose file takes the Dockerfile in the current directory and builds the container image from it.

# It specifies the build configuration for creating the container image from the source Dockerfile.

# • Builds from the `Dockerfile` in the current directory.


services:
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  app:
    restart: always
    build: .
    command: npm start
    ports:
      - "80:3000"
    links:
      - mongodb



