# FROM node:latest

# ENV NODE_ENV production
# ARG MONGODB_URI=$MONGODB_URI
# ENV MONGODB_URI=$MONGODB_URI
# ARG SECRET=$SECRET
# ENV SECRET=$SECRET
# ARG PORT=$PORT
# ENV PORT=$PORT

# RUN mkdir /app
# WORKDIR /app
# ADD . /app

# COPY package.json /app
# RUN npm install
# COPY . /app

# EXPOSE 80 3000

# CMD [ "npm", "start", "--host=0.0.0.0" ]
